language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-sgh' ]; then cd .. && eval "mv $currentfolder generator-sgh" && cd generator-sgh; fi

